CI: Improve configuration options
oss-review-toolkit/ort-ci-gitlab pull request #14
Opened 2022-04-18 06:05 UTC by janderssonse

This minor PR improves configuration options we discovered we needed when testing this, and I think could be useful for others, in what should be a fully backwards compatible way (the defaults values are the same as the current ci template):

- Makes the runner tag configurable by making it a var (default: docker) (for example, we would use other runner tags then docker, like k8s etc)
- Makes the downloader optional (default: enabled). This allows the user optionally use the default checkout of gitlab etc instead, as would be the use case if including it in a pipe etc NOTE: As GitLab does not allows naming the default checkout dir fully yet (the option ci_builds_dir  for runners is not enabled by default, see https://gitlab.com/gitlab-org/gitlab-runner/-/issues/4203, one might to need to change the project dir var when using this, as the user might not be able to set it to the default 'project'.
- advisor script failed in our runtime image due to a missing bash newline in the script, fixed

2022-04-21 20:37 UTC, tsteenbe commented
@janderssonse  Thank you for your contribution, also noticed now that in https://github.com/oss-review-toolkit/ort-gitlab-ci/issues/7 you mentioned https://github.com/janderssonse/ort-action which is 404'ing. 

Interested to develop with me on an official ORT GitHub action (https://github.com/oss-review-toolkit/ort/issues/3512)? If yes, please DM me on [ORT Slack](https://join.slack.com/t/ort-talk/shared_invite/enQtMzk3MDU5Njk0Njc1LThiNmJmMjc5YWUxZTU4OGI5NmY3YTFlZWM5YTliZmY5ODc0MGMyOWIwYmRiZWFmNGMzOWY2NzVhYTI0NTJkNmY).

2022-04-21 21:02 UTC, tsteenbe commented
Can you also improve the commit messages? The ORT maintainers like Git commits that make our mums proud ;-), see our [CONTRIBUTING.md](https://github.com/oss-review-toolkit/.github/blob/main/CONTRIBUTING.md#git-history) 

Below I listed some suggestions to improve the commit messages:

**Advisorscript: Fix missing newline**
```
ort-advisor: Fix missing newline which caused script failure
```

**CI: configurable runner** 
```
gitlab-ci: Make GitLab runner configurable

Make the runner tag configurable by the user so other names then the default "docker" can be used.
```

**CI: Optional ort downloader**
```
gitlab-ci: Make Downloader script conditional

Make executing the Downloader optional to allow use of the default checkout of GitLab. This is usefule when ORT for GitLab is run in a pipeline where the project code is already cloned on pipeline start up.

Note: As GitLab does not allow naming the default checkout directory yet (as option `ci_builds_dir` for runners is not enabled by default, see https://gitlab.com/gitlab-org/gitlab-runner/-/issues/4203), users might to need to change the project directory variable in case the user is not be able to set it to the default 'project'.
```

2022-04-21 21:02 UTC, tsteenbe requested changes

2022-04-21 21:02 UTC, tsteenbe commented on .gitlab-ci.yml
> +      "Runner tag for the gitlab runner, defaults to 'docker'"
Please change to  "Runner tag for the GitLab runner, defaults to 'docker'."

2022-04-21 21:05 UTC, tsteenbe commented
@janderssonse  Regarding the "Makes the downloader optional" am I understanding you right that you are executing ORT for GitLab's .gitlab-ci.yml directly in your project pipeline instead of using parent-child mechanism so it executes in your mirror of the ORT for GitLab pipeline?

2022-04-21 22:06 UTC, janderssonse commented
Thanks for the suggestions, will fix. Yes in the current runner for both GitLab and GitHub in the flow. 
A .gitlab.ci-file looks like this.

```
include: 
  - remote: <repoprojecturlwith-ci-files>/.ort-scan-template.yml
  - remote: <repoprojecturlwithci-files>/.post-bom-to-dependencytrack.yml

stages:
  - ....
  - ort-scan
  - upload-bom
  ....
```
  
  (And the ort-scan-template is a modification of the current one in the ort-gitlab-ci project. 
  https://github.com/janderssonse/ort-ci-action/blob/main/gitlab/.ort-scan-template.yml)

2022-04-29 12:16 UTC, zhernovs approved these changes

2022-05-12 12:02 UTC, janderssonse commented
Closing in this as we landed in other path after disussions.

2022-05-12 12:02 UTC, closed without merging